rm -f .env
touch .env
echo REACT_APP_VERSION=$REACT_APP_VERSION >> .env
echo GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP >> .env
echo REACT_APP_API_URL=$REACT_APP_API_URL >> .env
echo REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID >> .env
echo REACT_APP_BASE_URL=$REACT_APP_BASE_URL >> .env
